version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8044:8080

  api:
    image: archstyle
    ports:
      - 8080:8080
    environment:
      ARCHSTYLE_ENVIRONMENT: production

