# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/population.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import Empty_pb2 as google_dot_protobuf_dot_Empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/population.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/Empty.proto\"\xcc\x03\n\x0ePopulationData\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.PopulationData.Data\x12&\n\x06source\x18\x02 \x03(\x0b\x32\x16.PopulationData.Source\x1a\x44\n\x04\x44\x61ta\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0e\n\x06Nation\x18\x02 \x01(\t\x12\x0c\n\x04Year\x18\x04 \x01(\t\x12\x12\n\nPopulation\x18\x05 \x01(\r\x1a\x9d\x01\n\x0b\x41nnotations\x12\x13\n\x0bsource_name\x18\x01 \x01(\t\x12\x1a\n\x12source_description\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61taset_link\x18\x04 \x01(\t\x12\x10\n\x08table_id\x18\x05 \x01(\t\x12\r\n\x05topic\x18\x06 \x01(\t\x12\x10\n\x08subtopic\x18\x07 \x01(\t\x1a\x87\x01\n\x06Source\x12\x10\n\x08measures\x18\x01 \x03(\t\x12\x30\n\x0b\x61nnotations\x18\x02 \x01(\x0b\x32\x1b.PopulationData.Annotations\x12\x0c\n\x04name\x18\x03 \x01(\t\x12+\n\rsubstitutions\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any2S\n\x15PopulationDataService\x12:\n\rGetPopulation\x12\x16.google.protobuf.Empty\x1a\x0f.PopulationData\"\x00\x62\x06proto3')



_POPULATIONDATA = DESCRIPTOR.message_types_by_name['PopulationData']
_POPULATIONDATA_DATA = _POPULATIONDATA.nested_types_by_name['Data']
_POPULATIONDATA_ANNOTATIONS = _POPULATIONDATA.nested_types_by_name['Annotations']
_POPULATIONDATA_SOURCE = _POPULATIONDATA.nested_types_by_name['Source']
PopulationData = _reflection.GeneratedProtocolMessageType('PopulationData', (_message.Message,), {

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _POPULATIONDATA_DATA,
    '__module__' : 'protos.population_pb2'
    # @@protoc_insertion_point(class_scope:PopulationData.Data)
    })
  ,

  'Annotations' : _reflection.GeneratedProtocolMessageType('Annotations', (_message.Message,), {
    'DESCRIPTOR' : _POPULATIONDATA_ANNOTATIONS,
    '__module__' : 'protos.population_pb2'
    # @@protoc_insertion_point(class_scope:PopulationData.Annotations)
    })
  ,

  'Source' : _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
    'DESCRIPTOR' : _POPULATIONDATA_SOURCE,
    '__module__' : 'protos.population_pb2'
    # @@protoc_insertion_point(class_scope:PopulationData.Source)
    })
  ,
  'DESCRIPTOR' : _POPULATIONDATA,
  '__module__' : 'protos.population_pb2'
  # @@protoc_insertion_point(class_scope:PopulationData)
  })
_sym_db.RegisterMessage(PopulationData)
_sym_db.RegisterMessage(PopulationData.Data)
_sym_db.RegisterMessage(PopulationData.Annotations)
_sym_db.RegisterMessage(PopulationData.Source)

_POPULATIONDATASERVICE = DESCRIPTOR.services_by_name['PopulationDataService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POPULATIONDATA._serialized_start=84
  _POPULATIONDATA._serialized_end=544
  _POPULATIONDATA_DATA._serialized_start=178
  _POPULATIONDATA_DATA._serialized_end=246
  _POPULATIONDATA_ANNOTATIONS._serialized_start=249
  _POPULATIONDATA_ANNOTATIONS._serialized_end=406
  _POPULATIONDATA_SOURCE._serialized_start=409
  _POPULATIONDATA_SOURCE._serialized_end=544
  _POPULATIONDATASERVICE._serialized_start=546
  _POPULATIONDATASERVICE._serialized_end=629
# @@protoc_insertion_point(module_scope)
